### ISSUE TITLE
Exception there in main.py

### ISSUE THREAD

**Issue by arima-sambunath** [hellpanderrr/pdf2xml#2]
The Idea of pdf  to xml very impressive but one exception there when run this code at python2/3  

Traceback (most recent call last):
  File "pdf2xml.py", line 563, in <module>
    main(sys.argv)
  File "pdf2xml.py", line 90, in main
    tree = make_xml(objs,n,tree)
  File "pdf2xml.py", line 511, in make_xml
    xml = gen_xml(group_by(regobjs,n),n,xml)
  File "pdf2xml.py", line 421, in group_by
    for p in concave( sort_by_font (find_tables(objs)[0], 0 )[0],50,100)[0]:
  File "pdf2xml.py", line 206, in concave
    tmp.append(graph.nodes()[i])
  File "/home/sambhu/env-2demo/local/lib/python2.7/site-packages/networkx/classes/reportviews.py", line 178, in __getitem__
    return self._nodes[n]
KeyError: 8

**Comment by Hovera** [comment]
Yes, I have similar problem... 

File "/Users/Cutthroat/anaconda3/envs/python2_pdfminer/lib/python2.7/site-packages/networkx/classes/reportviews.py", line 178, in __getitem__
return self._nodes[n]
KeyError: 2

**Comment by huanghuanghui** [comment]
> The Idea of pdf to xml very impressive but one exception there when run this code at python2/3
> 
> Traceback (most recent call last):
> File "pdf2xml.py", line 563, in
> main(sys.argv)
> File "pdf2xml.py", line 90, in main
> tree = make_xml(objs,n,tree)
> File "pdf2xml.py", line 511, in make_xml
> xml = gen_xml(group_by(regobjs,n),n,xml)
> File "pdf2xml.py", line 421, in group_by
> for p in concave( sort_by_font (find_tables(objs)[0], 0 )[0],50,100)[0]:
> File "pdf2xml.py", line 206, in concave
> tmp.append(graph.nodes()[i])
> File "/home/sambhu/env-2demo/local/lib/python2.7/site-packages/networkx/classes/reportviews.py", line 178, in **getitem**
> return self._nodes[n]
> KeyError: 8

how to fix it?
